# AMQP Config Deamon
# Raphael Peters <rappet@rappet.de> 2021
#
# Receives configuration variables via AMQP, templates and
# applies the configuration

# source path of the template to apply
template_path = "testfiles/test.j2"

# destination path of the templated file
output_file = "testfiles/test.out"

# command to run after templating had been run
apply_command = "cat testfiles/test.out"

# AMQP broker URL
amqp_url = "amqp://127.0.0.1:5672/%2f"

# AMQP queue name
amqp_queue = "foobar"